#!/usr/bin/env bash
# =====================================================================
#  Kali-God-Mode — Shared helpers
#  Source this file from every module. Do not run directly.
# =====================================================================

# ---- Colors & logging ------------------------------------------------
GREEN='\e[32m'; YELLOW='\e[33m'; RED='\e[31m'; CYAN='\e[36m'; BOLD='\e[1m'; RESET='\e[0m'
log()  { echo -e "\n[${GREEN}+${RESET}] $*"; }
warn() { echo -e "[${YELLOW}!${RESET}] $*" >&2; }
err()  { echo -e "[${RED}-${RESET}] $*" >&2; }
info() { echo -e "[${CYAN}*${RESET}] $*"; }
section() { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════════════════════${RESET}"; echo -e "${BOLD}  $*${RESET}"; echo -e "${BOLD}${CYAN}══════════════════════════════════════════════════════════${RESET}"; }

# ---- Base paths ------------------------------------------------------
# TOOLKIT_ROOT = where installed tools live (~/Desktop/Kali-God-Mode)
TOOLKIT_ROOT="${KALI_GOD_MODE_ROOT:-$HOME/Desktop/Kali-God-Mode}"
SHARED_DIR="$TOOLKIT_ROOT/_shared"

# ---- Download helpers -------------------------------------------------
# Download a file; warns and continues instead of killing the script.
dl() {
    local url="$1" out="${2:-}"
    if [ -n "$out" ]; then
        wget -q --show-progress -O "$out" "$url" 2>&1 || { warn "Download failed: $url"; return 1; }
    else
        wget -q --show-progress "$url" 2>&1 || { warn "Download failed: $url"; return 1; }
    fi
}

# Download the latest GitHub release asset matching a regex pattern.
# Usage: gh_dl <owner/repo> <regex> [output_path]
gh_dl() {
    local repo="$1" pat="$2" out="${3:-}"
    local url
    url=$(curl -fsSL "https://api.github.com/repos/${repo}/releases/latest" 2>/dev/null \
          | grep -oE '"browser_download_url": *"[^"]+"' \
          | cut -d'"' -f4 | grep -iE "$pat" | head -n1)
    if [ -z "$url" ]; then warn "No release asset matching /$pat/ in $repo"; return 1; fi
    log "Fetching $(basename "$url")  (latest from $repo)"
    dl "$url" "$out"
}

# ---- Install helpers -------------------------------------------------
# Install an apt package, warning (not aborting) if unavailable.
apt_get() { sudo apt-get install -y "$@" 2>&1 | tail -1 || warn "apt could not install: $*"; }

# Install a pipx tool, warning (not aborting) on failure.
pipx_get() {
    local spec="$1" name="${2:-}"
    # Check if already installed
    if [ -n "$name" ] && command -v "$name" &>/dev/null; then
        info "$name already installed (skipping)"
        return 0
    fi
    log "pipx install $spec"
    pipx install "$spec" 2>/dev/null || pipx upgrade "${spec##*/}" 2>/dev/null \
        || warn "pipx could not install: $spec"
}

# Check if a tool is already available globally; returns 0 if found.
check_tool() { command -v "$1" &>/dev/null; }

# Log a skip message when a tool is already installed.
skip_tool() { info "$1 already installed globally (skipping)"; }

# ---- Directory helpers ------------------------------------------------
# Ensure a directory exists.
ensure_dir() { mkdir -p "$1" 2>/dev/null; }

# Create a symlink if the target exists and symlink doesn't already exist.
link_tool() {
    local src="$1" dst="$2"
    if [ -e "$src" ] && [ ! -e "$dst" ]; then
        ln -sf "$src" "$dst" 2>/dev/null && info "Linked: $dst -> $src"
    elif [ -e "$dst" ]; then
        info "Already linked: $dst"
    else
        warn "Source not found: $src"
    fi
}

# ---- Config helpers ---------------------------------------------------
# Append PATH entry to config.sh if not already present.
add_path_entry() {
    local entry="$1" config="$TOOLKIT_ROOT/config.sh"
    ensure_dir "$(dirname "$config")"
    grep -qF "$entry" "$config" 2>/dev/null || echo "export PATH=\"$entry:\$PATH\"" >> "$config"
}

# Append a line to the tools info file for a toolkit.
# Usage: add_tool_info <toolkit_dir> <tool_name> <run_command> <note>
add_tool_info() {
    local toolkit_dir="$1" name="$2" run_cmd="$3" note="${4:-}"
    local info_file="$toolkit_dir/tools-info.txt"
    ensure_dir "$toolkit_dir"
    printf "%-25s %-40s %s\n" "$name" "$run_cmd" "$note" >> "$info_file"
}

# ---- Credential capture -----------------------------------------------
# Write credentials to a toolkit's creds.txt.
# Usage: write_creds <toolkit_dir> <section_name> <lines...>
write_creds() {
    local toolkit_dir="$1" section="$2"; shift 2
    local creds_file="$toolkit_dir/creds.txt"
    ensure_dir "$toolkit_dir"
    {
        echo "=============================================================="
        echo " $section"
        echo " Generated by Kali-God-Mode"
        echo "=============================================================="
        printf '%s\n' "$@"
        echo
    } >> "$creds_file"
}
